channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.11.1
  - astunparse==1.6.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.1
  - pynvml==11.5.0
  - pyyaml==6.0.1
  - torch==2.2.1
  - tqdm==4.66.2
name: mlflow-env
